### ISSUE TITLE
Make sure links go to correct path on homepage

### ISSUE THREAD

**Issue by mattboitan0** [codeforamerica/primerpeso#125]
Hey Coqui coders :)

I was looking at your awesome website and saw that 2 of the links may not go to the place you want them to go - see below:

![screen shot 2014-09-22 at 10 04 23 am](https://cloud.githubusercontent.com/assets/6288109/4360314/b0878ec8-427a-11e4-9015-62a18b77ec41.png)

i.e. I'm assuming "Github Project" should go to https://github.com/codeforamerica/primerpeso and "Issues" should go to https://github.com/codeforamerica/primerpeso/issues. If that's not the case, no worries, but just wanted to flag.

Good luck this week!

**Comment by ainsleywagon** [comment]
@mattboitan0 thanks Matt!
