### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by MrMaksimize** [codeforamerica/primerpeso#38]
Hey guys,

Was just thinking on the train this morning.  We should really have a central reference document for coding style within our appication.  

I know of a few, but AFAIK airbnb's is the cleanest and best documented.

For CSS / LESS / SCSS we can probably use github's

https://github.com/styleguide/css

We can implement the linters once we agree.  

Thoughts -- @ainsleywagon @clarita1980 @chrisrodz

**Comment by ainsleywagon** [comment]
Definitely. I also need to make an overall page with colors and hover states, for everyone's info and my own consistency.

**Comment by MrMaksimize** [comment]
Ohhhh like http://style.codeforamerica.org/ :)

On Wed, Jul 16, 2014 at 1:47 PM, Ainsley notifications@github.com wrote:

> Definitely. I also need to make an overall page with colors and hover
> states, for everyone's info and my own consistency.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CoquiCoders/bizwallet/issues/38#issuecomment-49224593
> .

## 

_Maksim Pecherskiy_
Code For America http://codeforamerica.org | _Puerto Rico (team blog
http://coquicoders.org)_
_773.677.7755 || Schedule A Meeting https://calendly.com/maksim/ *
*@MrMaksimize http://twitter.com/MrMaksimize || MrMaksimize.com
http://mrmaksimize.com_
</>

**Comment by ainsleywagon** [comment]
Working on this: will update as I go with desired title/font sizes, etc.
![screen shot 2014-07-16 at 3 09 58 pm](https://cloud.githubusercontent.com/assets/1807325/3606375/f3c29c3e-0d35-11e4-92de-7475a1c68ac2.png)

**Comment by MrMaksimize** [comment]
Just putting these in to check out later, but might be kinda cool to autogen our style guide from less :)  

https://github.com/davidhund/styleguide-generators#user-content-nodejs
http://jacobrask.github.io/styledocco/
http://kaleistyleguide.com/
http://warpspire.com/posts/kss/

**Comment by ainsleywagon** [comment]
Done. View in documentation:
http://docs.primerpeso.org/docs/design_guide.html
