### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by MrMaksimize** [codeforamerica/primerpeso#76]
- [x] Contributing.md
- [x] Readme.md
- [x] Delete Schema.md
- [x] Controllers
- [x] Lib/OppQueryForm.js
- [x] lib/optionsList 
- [x] lib/sendRequestForm - > label
- [x] models/defs/Opportunity.js --> label
- [x] public/src/js/main.js
- [x] public/src/js/ppFormValidator.js
- [x] public/src/js/searcShop.js
- [x] public/src/js/search
- [x] views/

**Comment by clarita1980** [comment]
Readme I will leave it in english. This is standard.

**Comment by clarita1980** [comment]
I will not translate industries until we have the latest from NAICS
