### ISSUE TITLE
Wrap radio buttons in label

### ISSUE THREAD

**Issue by davidrleonard** [codeforamerica/primerpeso#94]
So when you hover over the text, and click it, it'll check the radio button
![radio-buttons](https://cloud.githubusercontent.com/assets/6456757/4069551/a2f45f3e-2e48-11e4-9a9b-b7937cfad10d.jpg)

**Comment by ainsleywagon** [comment]
Actually not sure how to do this within the jade/mixin method.
This is the code that generates the radio button field:
![screen shot 2014-09-08 at 10 50 22 am](https://cloud.githubusercontent.com/assets/1807325/4189929/cec0eb6e-3780-11e4-91ea-06b6dffbf506.png)
Not sure how to make wrapping happen when the thing that gets wrapped isn't there til later.
